INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('CE 100.1', 'CE Capstone Project I', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('CE 11', 'Introduction to Civil Engineering', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('CE 11A', 'Introduction to Civil Engineering, Lab', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('CE 22', 'Adv. Math for Civil Engineers', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('CE 22A', 'Adv. Math for Civil Engineers, Lab ', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('CE 31', 'Fundamentals of Surveying Lecture', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('CE 31A', 'Fundamentals of Surveying Lecture', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('CE 32', 'Highway & Railroad Engineering', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('CE 32A', 'Highway & Railroad Engineering', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('CE 33', 'Numerical Solutions to CE Problems', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('CE 33A', 'Numerical Solutions to CE Problems, Lab', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('CE 35', 'Building Systems Design', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('CE 35A', 'Building Systems Design', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('CE 36', 'Hydraulics', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('CE 36A', 'Hydraulics, Lab', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('CE 37', 'Construction Materials', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('CE 37A', 'Construction Materials, Lab', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('CE 38', 'Testing of Materials', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('CE 40', 'Quantity Surveying', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('CE 41', 'Structural Theory Lec', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('CE 41A', 'Structural Theory Lec, Lab', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('CE 42', 'Principles of Reinforced/Prestressed Concrete Design', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('CE 43', 'Principles of Transportation Engineering', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('CE 44', 'Principles of Steel Design', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('CE 50', 'Hydrology', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('CE 50A', 'Hydrology, Lab ', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('CE 52', 'Construction Methods & Project Mgt.', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('IT 69', 'Systems Administration and Maintenance', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('IT 71', 'Systems Integration and Architecture', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('IT61', 'Fundamentals of Database Systems', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('IT61A', 'Fundamentals of Database Systems, Lab', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('IT65', 'Information Assurance and Security 2', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('IT67', 'Integrative Programming and Technologies', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('ITIM 82', 'Big Data Analytics', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('ITIM 82A', 'Big Data Analytics, Lab', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('ITIM 83', 'Data Mining', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('ITIM 83A', 'Data Mining', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('ITIM 85', 'Special Topics in Information Management', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('ITIM 85A', 'Special Topics in Information Management', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('ITIM81', 'Programming for Data Science and AI', 40);
INSERT INTO `subjects` (`subject_id`, `subject_name`, `student_num`) VALUES ('ITIM81A', 'Programming for Data Science and AI, Lab', 40);
